### ISSUE TITLE
Change DDEV config to have a better composer ~2.0 , apache web server, and mariadb 10.11 database

### ISSUE THREAD

**Issue by Natshah** [Vardot/platformsh-varbase10x00#39]
### What in this template can be improved or added as a feature?

Better DDEV configs

### What exactly should be updated?

Change the .ddev/config.yml to have
Latest **Composer `~2.0`**
Switch web server to **Apache FPM**
Switch database to **mariadb `10.11`**

```
type: drupal10
docroot: docroot
webserver_type: apache-fpm
database:
  type: mariadb
  version: "10.11"
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment: []
php_version: "8.3"
nodejs_version: "18"
webimage_extra_packages: ["php${DDEV_PHP_VERSION}-yaml"]
dbimage_extra_packages: [sudo]

```

### How important is this feature to you?

Better match of working local development environments
